<?xml version="1.0" encoding="UTF-8"?><testrun name="MaxNumberTest" project="junit测试单元" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.lee.MaxNumberTest" time="0.001">
    <testcase name="testMax" classname="com.lee.MaxNumberTest" time="0.001">
      <failure>java.lang.AssertionError: expected same:&lt;5&gt; was not:&lt;6&gt;&#13;
	at org.junit.Assert.fail(Assert.java:74)&#13;
	at org.junit.Assert.failNotSame(Assert.java:444)&#13;
	at org.junit.Assert.assertSame(Assert.java:397)&#13;
	at org.junit.Assert.assertSame(Assert.java:407)&#13;
	at com.lee.MaxNumberTest.testMax(MaxNumberTest.java:17)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)&#13;
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)&#13;
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)&#13;
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)&#13;
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)&#13;
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)&#13;
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)&#13;
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
